name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: rc
        arguments: build
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: jfail
        path: build/libs
